---
title: "zm_baci_update"
author: "Denver Link"
date: "2024-12-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Library
```{r}
library(tidyverse)
library(mwlaxeref)
library(janitor)
library(mnsentinellakes)
library(sf)
library(brms)
```

# Data
```{r}
#mercury data
hg <- read_csv(file.path("G:", "Shared drives", "Hansen Lab", "RESEARCH PROJECTS", "Statewide mercury modeling", "Data", "Mercury Data", "allfish_data_04042024_JLO.csv")) %>% 
  filter(!(is.na(LGTHIN) | is.na(HGPPM) | is.na(DOWID))) %>%   #removes samples with no hg, length, or dow data
  filter(TYPE %in% c("Lake", "LAKE")) %>% 
  mutate(DOWID = fixlakeid(DOWID)) %>% 
  filter(DOWID != "16000100") %>% 
  local_to_nhdhr(from_colname = "DOWID", states = "mn") %>% 
  mutate(nhdhr.id = str_remove(nhdhr.id, "nhdhr_")) %>% 
  select(SAMPLENO,
         WATERWAY,
         TYPE,
         LOCATION,
         DOWID,
         nhdhr.id,
         DATECOL2,
         YEARCOLL,
         SPEC,
         ANATHG,
         NOFISH,
         LGTHIN,
         WTLB,
         AGE,
         SEX,
         HGPPM,
         HGCODE,
         HGLAB,
         HGCMMT) %>% 
  rename(DOW = DOWID,
         nhdid = nhdhr.id) %>% 
  ungroup()

#connection to covariates
dnr_covary <- read_csv(file.path("G:", "Shared drives", "Hansen Lab", "RESEARCH PROJECTS", "Statewide mercury modeling", "Data", "Covariate Data", "MN_lakes_watershed_lulc_fromDNR.csv")) %>% 
  mutate(logit_wetlands = car::logit(Percent_Wetland),
         logit_urban = car::logit(Percent_Urban),
         logit_ag = car::logit(Percent_Cultivated_Crops),
         log_WS_Lake_Ratio = log(WS_Lake_Ratio))

#scaled_dnr <- dnr_covary %>%
  #mutate_at(vars(Total_Pasture_Hay_Hectares:log_WS_Lake_Ratio), scale) %>% 
  #rename_with(~ paste0("scaled_", .), Total_Pasture_Hay_Hectares:log_WS_Lake_Ratio) 

#dnr_covary <- dnr_covary %>% 
  #left_join(scaled_dnr)

#adding dnr covariates into the data
hg <- hg %>% 
  left_join(dnr_covary)
rm(dnr_covary, scaled_dnr)

#glm - for clarity and area values
glm <- read_csv(file.path("G:", "Shared drives", "Hansen Lab", "RESEARCH PROJECTS", "Statewide mercury modeling", "Data", "Covariate Data", "glm_lake_metadata.csv")) %>%
  filter(state == "MN") %>% 
  rename(nhdid = site_id) %>% 
  mutate(nhdid = gsub("^nhdhr_", "", nhdid)) %>% 
  mutate(clarity = case_when(is.infinite(clarity) ~ NA,
                             TRUE ~ clarity)) %>% 
  mutate(log_area = log(area))


hg <- hg %>% 
  left_join(glm) %>% 
  mutate(across(starts_with("scaled_"), as.vector))
rm(glm)
glimpse(hg)

#infested waters list
zm <- read_csv("Data/ZM_MN_NHD.csv") %>% 
  filter(!is.na(DOW)) %>% 
  mutate(DOW = as.character(gsub("mndow_", "", MNDOW_ID)),
         nhdid = NHD_ID) %>% 
  select(DOW,
         Year_Infested) %>% 
  mutate(zm_lag_year_infested = Year_Infested +2)

hg <- hg %>% 
  left_join(zm, by = c("DOW"))
rm(zm)

#lake link
lake_link <- read_csv("Data/lake_link.csv") %>% 
  distinct(lake_nhdid, .keep_all = T) %>% 
  rename(nhdid = lake_nhdid)

lake_link_sf <- lake_link %>% 
  st_as_sf(coords = c("lake_lon_decdeg", "lake_lat_decdeg"), crs = 4326) %>% 
  st_transform(crs = 32615)
utm_coords <- st_coordinates(lake_link_sf)
lake_link <- lake_link %>%
  mutate(easting = utm_coords[, 1]/1000,
         northing = utm_coords[, 2]/1000)
#utm values in km instead of m
rm(lake_link_sf, utm_coords)

hg <- hg %>% 
  left_join(lake_link)
rm(lake_link)


#data for modeling - select for columns of use 
hg.model <- hg %>%
  select(WATERWAY,
         TYPE,
         DOW,
         nhdid,
         DATECOL2,
         YEARCOLL,
         SPEC,
         ANATHG,
         NOFISH,
         LGTHIN,
         HGPPM,
         Total_Wetland_Hectares,
         Percent_Wetland,
         Percent_Urban,
         Percent_Cultivated_Crops,
         logit_wetlands,
         logit_urban,
         logit_ag,
         WS_Lake_Ratio,
         log_WS_Lake_Ratio,
         centroid_lat,
         centroid_lon,
         max_depth,
         area,
         log_area,
         elevation,
         clarity,
         Year_Infested,
         zm_lag_year_infested,
         lake_lat_decdeg,
         lake_lon_decdeg,
         easting,
         northing) %>% 
  mutate(zm_lake = case_when(is.na(Year_Infested) ~ "n",
                             TRUE ~ "y"),
         zm_sample = case_when(zm_lag_year_infested <= YEARCOLL ~ "y",
                               TRUE ~ "n"),
         time_since_invasion = YEARCOLL - zm_lag_year_infested) %>% 
  clean_names()

rm(hg)
```

# Data Coverage
```{r}
# zebra mussel coverage
hg.model %>% 
  group_by(zm_lake) %>% 
  summarise(total_samples = n(),
            pre_zm = sum(zm_sample == "n"),
            post_zm = sum(zm_sample == "y"),
            distinct_lakes = n_distinct(dow),
            distinct_years = n_distinct(yearcoll))

#how many zm samples and lakes in 2023?
hg.model %>% 
  filter(zm_lake == "y" & yearcoll == "2023") %>% 
  summarise(zm_sampling_2023 = n(),
            zm_sampling_lakes_2023 = n_distinct(dow)
  )

#how many zebra mussel lakes have post data - how many years of post?
hg.model %>% 
  filter(zm_lake == "y") %>% 
  distinct(dow, zm_sample) %>% 
  group_by(dow) %>% 
  count() %>% 
  filter(n > 1)

hg.model %>% 
  filter(zm_lake == "y" & zm_sample == "y") %>% 
  group_by(dow) %>% 
  summarise(n_years = n_distinct(yearcoll)) %>% 
  ggplot() +
  geom_histogram(aes(x = n_years)) +
  geom_histogram(data = . %>% filter(dow == "48000200"), aes(n_years, fill = "red"))+
  theme(legend.position = "none")

#for lakes sampled in 2023 - how many years of post data do they have?
lakes_2023 <- hg.model %>% 
  filter(yearcoll == 2023 & zm_lake == "y") %>% 
  distinct(dow, waterway)

hg.model %>% 
  filter(dow %in% c(lakes_2023$dow)) %>% 
  filter(zm_sample == "y") %>% 
  group_by(dow) %>% 
  summarise(n_years = n_distinct(yearcoll)) %>% 
  ggplot() +
  geom_histogram(aes(n_years))
# 10/18 zebra mussel lake sampled in 2023 were sampled for the first time
rm(lakes_2023)
```

# Data for Analysis 
```{r}
#walleye zebra mussel data 
wae_zm_lakes <- hg.model %>% 
  filter(spec == "WAE") %>% 
  filter(yearcoll >= 2000) %>% 
  filter(zm_lake == "y") %>% 
  distinct(dow, zm_sample) %>% 
  group_by(dow) %>% 
  count() %>% 
  filter(n >1)
#this code chunk 1.) filters for walleye 2.) filters for years 2000-most recent 3.) filters for lakes invaded by zebra mussels 4.) finds the unique combinations for lake id and hg samples collected during zm invasion 5.) counts how many times a lake shows up - if it shows up 2x then it has both y and n for zm invasion samples 6.) filters for lakes that only have zm invasion 

wae_zm_fish <- hg.model %>% 
  filter(yearcoll >= 2000) %>%
  filter(spec == "WAE") %>% 
  filter(dow %in% c(wae_zm_lakes$dow))

#walleye reference lake 
wae_ref_lakes <- hg.model %>% 
  filter(spec == "WAE") %>% 
  filter(yearcoll >= 2000) %>% 
  filter(zm_lake == "n") %>% 
  #creating pseudo invasion based on middle year of the study
  mutate(zm_sample = case_when(yearcoll >= 2011 ~ "y",
                               yearcoll <= 2010 ~ "n")) %>% 
  distinct(dow, zm_sample) %>% 
  group_by(dow) %>% 
  count() %>% 
  filter(n >1)

wae_ref_fish <- hg.model %>% 
  filter(yearcoll >= 2000) %>%
  filter(spec == "WAE") %>% 
  filter(dow %in% c(wae_ref_lakes$dow)) %>% 
  mutate(zm_sample = case_when(yearcoll >= 2011 ~ "y",
                               yearcoll <= 2010 ~ "n"))

#######################northern pike#######################################
#pike zebra mussel data 
nop_zm_lakes <- hg.model %>% 
  filter(spec == "NOP") %>% 
  filter(yearcoll >= 2000) %>% 
  filter(zm_lake == "y") %>% 
  distinct(dow, zm_sample) %>% 
  group_by(dow) %>% 
  count() %>% 
  filter(n >1)
#this code chunk 1.) filters for pike 2.) filters for years 2000-most recent 3.) filters for lakes invaded by zebra mussels 4.) finds the unique combinations for lake id and hg samples collected during zm invasion 5.) counts how many times a lake shows up - if it shows up 2x then it has both y and n for zm invasion samples 6.) filters for lakes that only have zm invasion 

nop_zm_fish <- hg.model %>% 
  filter(yearcoll >= 2000) %>%
  filter(spec == "NOP") %>% 
  filter(dow %in% c(nop_zm_lakes$dow))

#walleye reference lake 
nop_ref_lakes <- hg.model %>% 
  filter(spec == "NOP") %>% 
  filter(yearcoll >= 2000) %>% 
  filter(zm_lake == "n") %>% 
  #creating pseudo invasion based on middle year of the study
  mutate(zm_sample = case_when(yearcoll >= 2011 ~ "y",
                               yearcoll <= 2010 ~ "n")) %>% 
  distinct(dow, zm_sample) %>% 
  group_by(dow) %>% 
  count() %>% 
  filter(n >1)

nop_ref_fish <- hg.model %>% 
  filter(yearcoll >= 2000) %>% 
  filter(spec == "NOP") %>% 
  filter(dow %in% c(nop_ref_lakes$dow))  %>% 
  mutate(zm_sample = case_when(yearcoll >= 2011 ~ "y",
                               yearcoll <= 2010 ~ "n"))

##############combined####################
baci_data <- bind_rows(nop_ref_fish, nop_zm_fish, wae_ref_fish, wae_zm_fish)
rm(nop_ref_fish, nop_zm_fish, wae_ref_fish, wae_zm_fish,
   nop_ref_lakes, nop_zm_lakes, wae_ref_lakes, wae_zm_lakes)

baci_data <- baci_data %>% 
  group_by(spec) %>% 
  mutate(scaled.length = c(scale(lgthin)))

###########quick QC##################################
baci_data %>% 
  group_by(yearcoll) %>% 
  count() %>% 
  print(n = nrow(.))

baci_data %>% 
  group_by(zm_lake, zm_sample) %>% 
  count()
```

Looks like there is some difference in the number of samples from Denver's master's tables and the data produced here - it is not explained by just he additional years - explore the filtering and data generating process if we wanted to explore further.

#Analysis 
```{r}
fit_1 <- brm(log(hgppm) ~ scaled.length*spec + zm_lake*zm_sample*spec + (1|dow) + (1|yearcoll), 
             data = baci_data, 
             family = gaussian(), 
             iter = 10000)
summary(fit_1)

######I have not run this model fit yet, but is an option
fit_2 <- brm(log(hgppm) ~ scaled.length*spec + zm_lake*time_since_invasion*spec + (1|dow) + (1|yearcoll))
```

